#!/bin/sh
. "$(dirname "$0")/_/husky.sh"


# Prettier
npm run prettier-staged

# Static Code Analysis
#sf scanner run --engine "pmd" --pmdconfig config/pmd.xml --severity-threshold 3  --target src/sobj/example --target src/sobj/core