name: Release Package

on:
  workflow_dispatch:

jobs:
  create_package_version:
    runs-on: ubuntu-latest
    env:
      SFDX_AUTH_URL_PACKAGING: ${{ secrets.SFDX_AUTH_URL_PACKAGING }}
      SF_USERNAME_PACKAGING: ${{ vars.SF_USERNAME_PACKAGING }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install SF CLI
        uses: kratapps/github-actions/install-sf-cli@main

      - name: Authenticate the packaging org
        run: echo "${SFDX_AUTH_URL_PACKAGING}" | sf auth sfdxurl store --sfdx-url-stdin

      - name: Create Managed Package Version
        run: |
          echo "Releasing version ${VERSION_NAME}"
          sf package1 version create --managed-released --package-id ${PACKAGE_ID} --name ${VERSION_NAME} --version ${VERSION_NAME} --target-org "${SF_USERNAME_PACKAGING}" --release-notes-url "${RELEASE_NOTES}" --wait 60
