name: Validate PR

on:
  pull_request:
    types: [opened, reopened, synchronize]
jobs:
  packaged:
    runs-on: ubuntu-latest
    env:
      SFDX_AUTH_URL: ${{ secrets.SFDX_AUTH_URL }}
      SF_USERNAME: ${{ vars.SF_USERNAME }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Configure Git Credentials
        run: |
          git config user.name 'github-actions[bot]'
          git config user.email 'github-actions[bot]@users.noreply.github.com'
          
      - name: Install SF CLI
        uses: kratapps/github-actions/install-sf-cli@main

      - name: Authorize packaging org
        run: echo "$SFDX_AUTH_URL" | sf auth sfdxurl store --sfdx-url-stdin

      - name: Validate against packaging org
        run: sf project deploy start --dry-run --test-level RunLocalTests --source-dir src/sobj/ --target-org ${SF_USERNAME}
  
  unpackaged:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure Git Credentials
        run: |
          git config user.name 'github-actions[bot]'
          git config user.email 'github-actions[bot]@users.noreply.github.com'

      - name: Install SF CLI
        uses: kratapps/github-actions/install-sf-cli@main

      - name: Create scratch org
        run: sf org create scratch --alias default --definition-file config/project-scratch-def.json --duration-days 1 --no-namespace

      - name: Deploy source
        run: sf project deploy start --target-org default --source-dir src/sobj/core/ --source-dir src/sobj/example/

      - name: Run Tests
        run: sf apex run test --target-org default --code-coverage --test-level RunLocalTests --result-format human
  
  static-code-analysis:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Install node dependencies
        run: npm install
          
      - name: Run scanner
        run: sf scanner run --engine "pmd" --pmdconfig config/pmd.xml --severity-threshold 3 --target src/sobj/example --target src/sobj/core
        
  prettier-verify:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install node dependencies
        run: npm install 
        
      - name: Prettier Verify
        run: node_modules/prettier/bin-prettier.js --check --config .prettierrc "**/*.{cls,js,json}"